name: Find Secrets
on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master
        env:
         WORKSPACE: ""
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        with:
         output: reports
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: secret-scan-reports
          path: reports
