name: VulnAlerts

on: push
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: y-mehta/vulnalerts@master
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
    - name: done
      run: echo 'done'
