name: "trufflehog"

on: push

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - uses: actions/checkout@master
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
		with:
		scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*
