name: "trufflehog"

on: push

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
- uses: actions/checkout@master
- name: trufflehog-actions-scan
  uses: edplato/trufflehog-actions-scan@master
